language: node_js
node_js:
  - "8"
  - "6"
  - "node"
sudo: required
services:
  - docker
before_install:
  - docker run -d -p 9411:9411 openzipkin/zipkin
  - while netstat -lnt | awk '$4 ~ /:9411$/ {exit 1}'; do sleep 10; done
